export const projects = [
  {
    title: 'Modern UX/UI GPT-3',
    description: "Modern UX/UI GPT-3 is a complete responsive website made by Front-end technologies such as HTML,CSS and React",
      image: '/images/1.png',
      tags: ['HTMl','CSS', 'React'],
    source: 'https://github.com/venkateswarlu589/Modern-UI-UX-GPT-3',
    visit: 'https://modern-ui-ux-gpt-3-tan.vercel.app/',
    id: 0,
  },
  {
    title: 'Rock paper Scissors',
    description:"A Rock, Paper, Scissors game is a classic hand game often used as a simple decision-making tool between two people. The game has three possible outcomes, each of which defeats one of the other choices",
    image: '/images/2.png',
    tags: ['HTML','CSS','React', 'JavaScript'],
    source: 'https://github.com/venkateswarlu589/rock-paper-scissors-human-vs-ai-',
    visit: 'https://rock-paper-scissors-human-vs-ai.vercel.app/',
    id: 1,
  },
  {
    title: 'Analog-Clock',
    description: "An analog clock is a traditional timekeeping device that displays the current time using hour, minute, and sometimes second hands, arranged on a circular dial.",
      image: '/images/3.png',
      tags: ['HTMl','CSS','JavaScript'],
    source: 'https://github.com/venkateswarlu589/analog-clock',
    visit: 'https://analog-clock-swart-iota.vercel.app/',
    id: 2,
  },
  {
    title: '3D-Portfolio',
    description: "A 3D-portfolio, in the context of a creative career, is a curated collection of my work, accomplishments, skills and experiences.",
    image: '/images/4.png',
    tags: ['HTMl','TailwindCSS','JavaScript','React','ThreeJs'],
    source: 'https://github.com/venkateswarlu589/3d_portfolio',
    visit: 'https://3d-portfolio-chi-lovat.vercel.app/',
    id: 4,
  },
  {
    title: 'Oppenheimer Slide animation',
    description:"Oppenheimerheimer slide animation is developed by html,css animations and javascript concepts",
    image: '/images/5.png',
    tags: ['HTML','CSS','JavaScript'],
    source: 'https://github.com/venkateswarlu589/oppenheimer_slideranimation',
    visit: 'https://oppenheimer-slideranimation.vercel.app/',
    id: 5,
  },
  {
    title: 'Intersteller Slideshow',
    description: "Intersteller slideshow is developed by html,css animations and javascript concepts",
    image: '/images/6.png',
    tags: ['HTMl','CSS','JavaScript'],
    source: 'https://github.com/venkateswarlu589/intersteller_animation',
    visit: 'https://intersteller-nimation.vercel.app/',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Worked on responsive webdesigning and problem solving', },
  { year: 2021, text: 'Built Websites Using Front-end technologies', },
  { year: 2022, text: 'Worked on Back-end technologies like Node and Databases ', },
  { year: 2023, text: 'Gained practical experience by contributing to projects on github' },
];